server:
  port: 8080
  error:
    include-message: always
  servlet:
    context-path: /api/mono/
  ssl:
    enabled: false


spring:
  jpa:
    show-sql: true
    # mySQL
    # database: mysql
    # database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true





  datasource:
    url: jdbc:postgresql://localhost:5432/btf
    username: postgres
    password: 1234

  ## mySQl settings
  # username: root
  # password: root
  # url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/btf_spring_mono_db

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS


# Because no one likes that default petstore
springdoc:
  swagger-ui:
    #config-url: true
    disable-swagger-default-url: true

application:
  config:
    jwt:
      secretKey: thisIsTheSecretWhichWillBeRemovedFromHere
      tokenPrefix: Bearer
      tokenExpirationAfterDays: 30